### ISSUE TITLE
qshell m3u8replace command error

### ISSUE THREAD

**Issue by tuesleep** [qiniu/qshell#211]
- system: macOS Mojave 10.14.1 (18B75)
- terminal: oh-my-zsh

my command:

```
qshell_darwin_x64 m3u8replace ts666 output/index.m3u8 http://hls.example.com
```

Error detail:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x13626fa]

goroutine 1 [running]:
github.com/qiniu/api.v7/storage.(*FormUploader).put(0xc000146df8, 0x0, 0x0, 0x1523980, 0xc0001ee090, 0xc0001f0000, 0x92, 0x7ffeefbff87c, 0x11, 0xc000146c01, ...)
	/Users/caijiaqiang/go/pkg/mod/github.com/qiniu/api.v7@v7.2.6-0.20181128092015-8c3e1ca2eb33+incompatible/storage/form_upload.go:164 +0x3a
github.com/qiniu/api.v7/storage.(*FormUploader).Put(0xc000146df8, 0x0, 0x0, 0x1523980, 0xc0001ee090, 0xc0001f0000, 0x92, 0x7ffeefbff87c, 0x11, 0x16bdb00, ...)
	/Users/caijiaqiang/go/pkg/mod/github.com/qiniu/api.v7@v7.2.6-0.20181128092015-8c3e1ca2eb33+incompatible/storage/form_upload.go:139 +0x113
github.com/qiniu/qshell/iqshell.(*BucketManager).M3u8ReplaceDomain(0xc00000e2b8, 0x7ffeefbff876, 0x5, 0x7ffeefbff87c, 0x11, 0x7ffeefbff88e, 0x10, 0x0, 0x0)
	/Users/caijiaqiang/go/src/github.com/qiniu/qshell/iqshell/m3u8.go:191 +0xe78
github.com/qiniu/qshell/cmd.M3u8Replace(0x1a8bca0, 0xc000150a50, 0x3, 0x3)
	/Users/caijiaqiang/go/src/github.com/qiniu/qshell/cmd/rs.go:464 +0xd3
github.com/spf13/cobra.(*Command).execute(0x1a8bca0, 0xc000150960, 0x3, 0x3, 0x1a8bca0, 0xc000150960)
	/Users/caijiaqiang/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2cc
github.com/spf13/cobra.(*Command).ExecuteC(0x1a87a20, 0x1a8fa60, 0x0, 0x1a91220)
	/Users/caijiaqiang/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2fd
github.com/spf13/cobra.(*Command).Execute(0x1a87a20, 0xc000147f48, 0xc000147f88)
	/Users/caijiaqiang/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800 +0x2b
main.main()
	/Users/caijiaqiang/go/src/github.com/qiniu/qshell/main.go:10 +0x31
```

How to fix this error ? need help, thanks!

And the m3u8 file content:

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-ALLOW-CACHE:YES
#EXT-X-TARGETDURATION:3
#EXTINF:2.908422,
video-000.ts
#EXTINF:1.905422,
video-001.ts
#EXTINF:2.005422,
video-002.ts
#EXTINF:2.005422,
video-003.ts
#EXTINF:1.772422,
video-004.ts
#EXTINF:1.905422,
video-005.ts
#EXTINF:1.905422,
video-006.ts
#EXTINF:1.944422,
video-007.ts
#EXTINF:1.871422,
video-008.ts
#EXTINF:1.838422,
video-009.ts
#EXTINF:2.005422,
video-010.ts
#EXTINF:2.708422,
video-011.ts
#EXTINF:1.771422,
video-012.ts
#EXTINF:2.005422,
video-013.ts
#EXTINF:1.704422,
video-014.ts
#EXTINF:1.804422,
video-015.ts
#EXT-X-ENDLIST
```

**Comment by tonycai653** [comment]
这个是替换域名，但是你的ts文件都没有域名，所以报错了

**Comment by tonycai653** [comment]
http://devtools.qiniu.com/qshell-v2.3.6.zip 下载这个develop版本使用下

**Comment by tuesleep** [comment]
No contain `qshell_darwin_x64` ?  
Use `qshell_linux_x64` got error: `zsh: exec format error: qshell_linux_x64`

**Comment by tonycai653** [comment]
在重新下载下， 清除下浏览器缓存

**Comment by tuesleep** [comment]
qshell_darwin_x64 没有在 qshell-v2.3.6.zip 里面。
我用源码 make install 之后，可以使用了。

**Comment by tonycai653** [comment]
ok
