### ISSUE TITLE
qshell user ls

### ISSUE THREAD

**Issue by La-fe** [qiniu/qshell#317]
#### 问题描述
阿里云服务器, 镜像新服务使用 qshell user ls 产生下列错误
lsuser: open db: <nil>

使用 qshell user cu dev
出现
panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x82d567d]

goroutine 1 [running]:
github.com/syndtr/goleveldb/leveldb.(*DB).setClosed(...)
	/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db_state.go:225
github.com/syndtr/goleveldb/leveldb.(*DB).Close(0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:1117 +0x1d
panic(0x85f2920, 0x8adb9f0)
	/usr/local/go/src/runtime/panic.go:965 +0x15c
github.com/syndtr/goleveldb/leveldb.(*DB).isClosed(...)
	/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db_state.go:230
github.com/syndtr/goleveldb/leveldb.(*DB).ok(...)
	/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db_state.go:235
github.com/syndtr/goleveldb/leveldb.(*DB).Get(0x0, 0xa147e20, 0x3, 0x20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:838 +0x5b
github.com/qiniu/qshell/v2/iqshell.ChUser(0xffbe0202, 0x3, 0x0, 0x0)
	/github/workspace/iqshell/account.go:303 +0x167
github.com/qiniu/qshell/v2/cmd.ChUser(0x8ae4500, 0xa09f480, 0x1, 0x1)
	/github/workspace/cmd/user.go:70 +0x35
github.com/spf13/cobra.(*Command).execute(0x8ae4500, 0xa09f470, 0x1, 0x1, 0x8ae4500, 0xa09f470)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x1ec
github.com/spf13/cobra.(*Command).ExecuteC(0x8ae61e0, 0x8051c4f, 0xa094030, 0x0)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x29a
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
main.main()
	/github/workspace/main.go:11 +0x27

#### 相关环境信息
- **操作系统**：
- LSB Version:	core-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic

- **qshell版本**: qshell-v2.6.1-linux-386.tar.gz

**Comment by La-fe** [comment]
解决了, 镜像服务器之后 需要先 qshell user clean, 再重新加入账号
